// frontend-react/src/index.js
import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css'; // This will be generated by Tailwind CSS build
import App from './app';

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);